/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 439ff6c401da77a7efe2343e29c23fae)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ENV: "production" | "development";
	AUTH_SECRET: string;
	ADMIN_EMAIL: string;
	ADMIN_PASSWORD: string;
	MAINTENANCE_MODE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface ProductionEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		APP_ENV: "production";
		AUTH_SECRET: string;
		ADMIN_EMAIL: string;
		ADMIN_PASSWORD: string;
		MAINTENANCE_MODE: string;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "AUTH_SECRET" | "ADMIN_EMAIL" | "ADMIN_PASSWORD" | "MAINTENANCE_MODE">> {}
}
